version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.4
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  pgAdmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4:7.5
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
